app/books/forms.py
# app/books/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class SearchForm(FlaskForm):
    """
    Form to search the database
    """
    searchby = SelectField('Buscar por ', choices=[('0','Título'),('1','Género'),
                                       ('2','Autor'),('3','Editorial'),
                                       ('4','Ubicación'),('5','Comentario')])
    title = StringField('', validators=[DataRequired()])
    submit = SubmitField('Buscar')

app/books/__init__.py
# app/books/__init__.py

from flask import Blueprint

books = Blueprint('books', __name__)

from . import views

app/books/views.py
# app/books/views.py

from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import books
from .forms import SearchForm
from .. import db
from ..models import Book

@books.route('/search', methods=['GET', 'POST'])
def search():
    """
    Search the database
    """
    form = SearchForm()

    if form.validate_on_submit():
        try:
            # search database
            question = '%'+form.title.data+'%'

            if form.searchby.data == '0':
                search_results = Book.query.filter(Book.title.ilike(question))
            elif form.searchby.data == '1':
                search_results = Book.query.filter(Book.genre.ilike(question))
            elif form.searchby.data == '2':
                search_results = Book.query.filter(Book.author.ilike(question))
            elif form.searchby.data == '3':
                search_results = Book.query.filter(Book.publisher.ilike(question))
            elif form.searchby.data == '4':
                search_results = Book.query.filter(Book.location.ilike(question))
            elif form.searchby.data == '5':
                search_results = Book.query.filter(Book.comment.ilike(question))

            flash('Busqueda exitosa.')
        except:
            # something goes wrong
            flash('Error: something went wrong.')

        # redirect to results page
        return list_results(search_results)

    return render_template('books/search.html', action="Search", form=form,
                           title="Busqueda")

def list_results(search_results):
    """
    List search results
    """
    return render_template('books/search_results.html',
                           search_results=search_results,
                           title="Resultados de busqueda")

@books.route('/books/view/<int:id>', methods=['GET'])
def single_view(id):
    """
    Single results view
    """
    book = Book.query.get_or_404(id)

    title_is_abridged = False
    author_is_abridged = False
    title_abridged = book.title
    author_abridged = book.author

    if len(title_abridged) > 24:
        title_abridged = title_abridged[:24] + '...'
        title_is_abridged = True

    if len(author_abridged) > 30:
        author_abridged = author_abridged[:30] + '...'
        author_is_abridged = True

    return render_template('books/single_view.html',
                           book=book,
                           title_is_abridged=title_is_abridged,
                           author_is_abridged=author_is_abridged,
                           title_abridged=title_abridged,
                           author_abridged=author_abridged,
                           title="Vista singular")

app/templates/books/search.html
<!-- app/templates/books/search.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Busqueda{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Buscar en la biblioteca</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/books/search_results.html
<!-- app/templates/books/search_results.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Resultados de busqueda{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Resultados de busqueda</h1>
        {% if search_results %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="45%"> Título </th>
                  <th width="10%"> Género </th>
                  <th width="10%"> Autor </th>
                  <th width="10%"> Editorial </th>
                  <th width="5%"> Ubicación </th>
                  <th width="10%"> Comentario </th>
                  {% if current_user.is_admin %}
                    <th width="5%"> Editar </th>
                    <th width="5%"> Borrar </th>
                  {% endif %}
                </tr>
              </thead>
              <tbody>
              {% for result in search_results %}
                <tr>
                  <td> <a href="{{ url_for('books.single_view', id=result.id)}}">{{ result.title }}</a> </td>
                  <td> {{ result.genre }} </td>
                  <td> {{ result.author }} </td>
                  <td> {{ result.publisher }} </td>
                  <td> {{ result.location }} </td>
                  <td> {{ result.comment }} </td>
                  {% if current_user.is_admin %}
                    <td>
                      <a href="{{ url_for('admin.edit_book', id=result.id) }}">
                        <i class="fa fa-pencil"></i> Editar 
                      </a>
                    </td>
                    <td>
                      <a href="{{ url_for('admin.delete_book', id=result.id) }}">
                        <i class="fa fa-trash"></i> Borrar 
                      </a>
                    </td>
                  {% endif %}
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No se encontraron resultados. </h3>
            <hr class="intro-divider">
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/books/single_view.html
<!-- app/templates/books/single_view.html -->

{% extends "base.html" %}
{% block title %}Vista singular{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center-singleview">
          <div class="image-frame"></div>
          <div class="info-frame">
            <br/>
            {% if title_is_abridged %}
              <div class="popup" onclick="openPopup('popupFullTitle')">
                <h1>{{ title_abridged }}</h1>
                <span class="popuptext" id="popupFullTitle">
                  <span id="fullTitle">{{ book.title }}</span>
                  <br/>
                  <br/>
                  <a href="#" class="btn btn-default btn-lg" onclick="copyToClipboard('fullTitle')">
                    <i class="fa fa-clipboard"></i></a>
                </span>
              </div>
            {% else %}
              <h1>{{ title_abridged }}</h1>
            {% endif %}
            {% if author_is_abridged %}
              <div class="popup" onclick="openPopup('popupFullAuthor')">
                <h2>por {{ author_abridged }}</h2>
                <span class="popuptext" id="popupFullAuthor">
                  <span id="fullAuthor">{{ book.author }}</span>
                  <br/>
                  <br/>
                  <a href="#" class="btn btn-default btn-lg" onclick="copyToClipboard('fullAuthor')">
                    <i class="fa fa-clipboard"></i></a>
                </span>
              </div>
            {% else %}
              <h2>por {{ author_abridged }}</h2>
            {% endif %}
            <br/>
            <br/>
            <br/>
            Género: {{ book.genre }}<br/>
            Editorial: {{ book.publisher }}<br/>
            Ubicación: {{ book.location }}<br/>
            Comentario: {{ book.comment }}<br/>
            <br/>
            {% if current_user.is_admin %}
              <a href="{{ url_for('admin.edit_book', id=book.id) }}" class="btn btn-default btn-lg">
                <i class="fa fa-pencil"></i> Editar </a>
              <a href="{{ url_for('admin.delete_book', id=book.id) }}" class="btn btn-default btn-lg">
                <i class="fa fa-trash"></i> Borrar </a>
            {% endif %}
            <br/>
            <br/>
            <a href="#" class="btn btn-default btn-lg" onclick="window.history.back()">
              <i class="fa fa-arrow-left"></i> Regresar </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
function openPopup(elementName) {
    var popup = document.getElementById(elementName);
    popup.classList.toggle("show");
}
function copyToClipboard(elementName) {
  /* Get the text field */
  var copyText = document.getElementById(elementName).textContent;
  var dummy = document.createElement("input");

  document.body.appendChild(dummy);
  dummy.setAttribute('value', copyText);
  dummy.select();
  document.execCommand("Copy");
  document.body.removeChild(dummy);

  /* Alert the copied text */
  alert("Se copió el texto: " + copyText);
} 
</script>
{% endblock %}